# Generated by Django 2.2.13 on 2020-09-19 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_accountstatus_user_name'),
        ('profiles', '0015_auto_20180423_0727'),
    ]

    operations = [
    ]
